// packages/tui-solid/src/table.tsx
import { createEffect, createSignal, For, type JSX } from "solid-js";
import {
  SelectionMachine,
  computeVirtualWindow,
  cycleSort,
  formatCell,
  orderRows,
  resolveColumnWidths,
} from "@uniview/tui-core";
import type { Column, ColumnSpec, TableProps, TuiKeyEvent } from "@uniview/tui-core";
import { Box, Text } from "./primitives";

// Shared shapes from @uniview/tui-core, re-exported so tui-solid mirrors
// tui-react's surface.
export type { Column, TableProps, ColumnAlign, SortDirection, SortState } from "@uniview/tui-core";

function intrinsicWidth<T>(columns: readonly Column<T>[], gap: number): number {
  const cells = columns.reduce((sum, c) => sum + (c.width ?? c.minWidth ?? 8), 0);
  return cells + gap * Math.max(0, columns.length - 1);
}

/**
 * The Solid port of tui-react's `Table`: same controlled props, same box/text
 * output, same virtualization. Props are never destructured (that would
 * snapshot them and break fine-grained reactivity), and the windowed rows are
 * rendered with `<For>` so the reconciler has row identity.
 */
export function Table<T>(props: TableProps<T>): JSX.Element {
  const columnGap = (): number => props.columnGap ?? 1;
  const overscan = (): number => props.overscan ?? 0;
  const showHeader = (): boolean => props.showHeader ?? true;

  const order = (): number[] => {
    const sort = props.sort;
    const column = sort ? props.columns.find((c) => c.key === sort.columnKey) : undefined;
    return sort && column?.sort
      ? orderRows(props.rows, column.sort, sort.direction)
      : props.rows.map((_, i) => i);
  };

  const total = (): number =>
    typeof props.width === "number" ? props.width : intrinsicWidth(props.columns, columnGap());
  const resolved = (): ReturnType<typeof resolveColumnWidths> =>
    resolveColumnWidths(props.columns as readonly ColumnSpec[], total(), columnGap());

  const [scrollTop, setScrollTop] = createSignal(0);
  const maxScroll = (): number => Math.max(0, order().length - props.height);

  // Roving cursor, re-synced to the controlled prop inside an effect.
  const machine = new SelectionMachine({
    count: order().length,
    selectedIndex: props.selectedIndex,
    pageSize: props.height,
  });
  createEffect(() => {
    machine.setCount(order().length);
    machine.setPageSize(props.height);
    machine.setSelectedIndex(props.selectedIndex);
  });

  createEffect(() => {
    const selected = props.selectedIndex;
    const view = props.height;
    const max = maxScroll();
    setScrollTop((top) => {
      if (selected < top) return selected;
      if (selected >= top + view) return selected - view + 1;
      return Math.min(top, max);
    });
  });

  const onKeyDown = (event: TuiKeyEvent): void => {
    const effects = machine.handle({
      type: "key",
      key: event.key,
      ctrl: event.ctrl,
      alt: event.alt,
      shift: event.shift,
      meta: event.meta,
    });
    for (const effect of effects) props.onSelect(effect.index);
  };

  const window = (): ReturnType<typeof computeVirtualWindow> =>
    computeVirtualWindow({
      itemCount: order().length,
      itemHeight: 1,
      viewportHeight: props.height,
      scrollTop: scrollTop(),
      overscan: overscan(),
    });

  const visible = (): number[] => {
    const { startIndex, endIndex } = window();
    const out: number[] = [];
    for (let i = startIndex; i <= endIndex; i += 1) out.push(i);
    return out;
  };

  return (
    <Box
      onKeyDown={onKeyDown}
      role="table"
      autoFocus={props.autoFocus}
      flexDirection="column"
      width={props.width}
      height={(showHeader() ? 1 : 0) + props.height}
    >
      {showHeader() ? (
        <Box role="row" flexDirection="row" gap={columnGap()}>
          <For each={props.columns}>
            {(column, i) => {
              const arrow = (): string => {
                const sort = props.sort;
                return sort && sort.columnKey === column.key ? (sort.direction === "asc" ? " ▲" : " ▼") : "";
              };
              const sortable = (): boolean => Boolean(props.onSortChange && column.sort);
              return (
                <Text
                  role="columnheader"
                  bold
                  onClick={sortable() ? () => props.onSortChange!(cycleSort(props.sort ?? null, column.key)) : undefined}
                >
                  {formatCell(column.header + arrow(), resolved()[i()]!.width, column.align ?? "left")}
                </Text>
              );
            }}
          </For>
        </Box>
      ) : null}
      <For each={visible()}>
        {(i) => {
          const row = (): T => props.rows[order()[i]!]!;
          const selected = (): boolean => i === props.selectedIndex;
          const name = (): string | undefined => (props.rowName ? props.rowName(row(), i) : undefined);
          return (
            <Box
              role="row"
              name={name()}
              selected={selected()}
              flexDirection="row"
              gap={columnGap()}
              width="100%"
              backgroundColor={selected() ? (props.selectedBackground ?? "blue") : undefined}
              onClick={() => props.onSelect(i)}
            >
              <For each={props.columns}>
                {(column, ci) => (
                  <Text color={selected() ? props.selectedColor : column.color}>
                    {formatCell(column.accessor(row()), resolved()[ci()]!.width, column.align ?? "left")}
                  </Text>
                )}
              </For>
            </Box>
          );
        }}
      </For>
    </Box>
  );
}

// packages/tui-react/src/table.ts
import { createElement, useEffect, useRef, useState, type ReactElement, type ReactNode } from "react";
import {
  SelectionMachine,
  computeVirtualWindow,
  cycleSort,
  formatCell,
  orderRows,
  resolveColumnWidths,
} from "@uniview/tui-core";
import type { Column, ColumnSpec, TableProps } from "@uniview/tui-core";
import type { TuiKeyEvent } from "./primitives";

// The row/column shapes live in @uniview/tui-core so React and Solid cannot
// drift; re-exported here so tui-react's public API is self-contained.
export type { Column, TableProps, ColumnAlign, SortDirection, SortState } from "@uniview/tui-core";

/** Total content width when the caller did not pin one: summed column widths + gaps. */
function intrinsicWidth<T>(columns: readonly Column<T>[], gap: number): number {
  const cells = columns.reduce((sum, c) => sum + (c.width ?? c.minWidth ?? 8), 0);
  return cells + gap * Math.max(0, columns.length - 1);
}

/**
 * A controlled, virtualized, selectable data table built from box/text. The
 * cursor is a shared {@link SelectionMachine}; rows are windowed with
 * {@link computeVirtualWindow} so only the visible slice paints, however many
 * rows there are; columns are laid out and formatted by the tui-core helpers.
 * Optional controlled column sort (`sort`/`onSortChange`) reorders rows;
 * clicking a sortable header cycles it. Arrow/Home/End/PageUp/PageDown move the
 * cursor and the viewport follows it.
 */
export function Table<T>(props: TableProps<T>): ReactElement {
  const {
    columns,
    rows,
    selectedIndex,
    onSelect,
    height,
    width,
    columnGap = 1,
    overscan = 0,
    showHeader = true,
    selectedBackground = "blue",
    selectedColor,
    rowName,
    sort = null,
    onSortChange,
    autoFocus,
  } = props;

  // Sort order: a permutation of row indices in the current display order.
  const activeColumn = sort ? columns.find((c) => c.key === sort.columnKey) : undefined;
  const order =
    sort && activeColumn?.sort ? orderRows(rows, activeColumn.sort, sort.direction) : rows.map((_, i) => i);

  const total = typeof width === "number" ? width : intrinsicWidth(columns, columnGap);
  const resolved = resolveColumnWidths(columns as readonly ColumnSpec[], total, columnGap);

  const [scrollTop, setScrollTop] = useState(0);
  const maxScroll = Math.max(0, order.length - height);

  // Roving cursor. Re-synced to the controlled prop AFTER commit (in an effect,
  // like List) so back-to-back synchronous keys compose before the prop lands.
  const machineRef = useRef<SelectionMachine | null>(null);
  const machine = (machineRef.current ??= new SelectionMachine({
    count: order.length,
    selectedIndex,
    pageSize: height,
  }));
  useEffect(() => {
    machine.setCount(order.length);
    machine.setPageSize(height);
    machine.setSelectedIndex(selectedIndex);
  }, [machine, order.length, height, selectedIndex]);

  // Keep the cursor inside the viewport (List's clamp).
  useEffect(() => {
    setScrollTop((s) => {
      if (selectedIndex < s) return selectedIndex;
      if (selectedIndex >= s + height) return selectedIndex - height + 1;
      return Math.min(s, maxScroll);
    });
  }, [selectedIndex, height, maxScroll]);

  const onKeyDown = (event: TuiKeyEvent): void => {
    const effects = machine.handle({
      type: "key",
      key: event.key,
      ctrl: event.ctrl,
      alt: event.alt,
      shift: event.shift,
      meta: event.meta,
    });
    for (const effect of effects) onSelect(effect.index);
  };

  const out: ReactNode[] = [];

  if (showHeader) {
    const headerCells = columns.map((column, i) => {
      const arrow = sort && sort.columnKey === column.key ? (sort.direction === "asc" ? " ▲" : " ▼") : "";
      const label = formatCell(column.header + arrow, resolved[i]!.width, column.align ?? "left");
      const sortable = Boolean(onSortChange && column.sort);
      return createElement(
        "text",
        {
          key: column.key,
          role: "columnheader",
          bold: true,
          onClick: sortable ? () => onSortChange!(cycleSort(sort, column.key)) : undefined,
        },
        label,
      );
    });
    out.push(
      createElement("box", { key: "__header", role: "row", flexDirection: "row", gap: columnGap }, ...headerCells),
    );
  }

  const window = computeVirtualWindow({
    itemCount: order.length,
    itemHeight: 1,
    viewportHeight: height,
    scrollTop,
    overscan,
  });
  for (let i = window.startIndex; i <= window.endIndex; i += 1) {
    const displayIndex = i;
    const row = rows[order[i]!]!;
    const selected = i === selectedIndex;
    const cells = columns.map((column, ci) =>
      createElement(
        "text",
        { key: column.key, color: selected ? selectedColor : column.color },
        formatCell(column.accessor(row), resolved[ci]!.width, column.align ?? "left"),
      ),
    );
    const name = rowName ? rowName(row, displayIndex) : undefined;
    out.push(
      createElement(
        "box",
        {
          key: name ?? displayIndex,
          role: "row",
          name,
          selected,
          flexDirection: "row",
          gap: columnGap,
          width: "100%",
          backgroundColor: selected ? selectedBackground : undefined,
          onClick: () => onSelect(displayIndex),
        },
        ...cells,
      ),
    );
  }

  return createElement(
    "box",
    { onKeyDown, role: "table", autoFocus, flexDirection: "column", width, height: (showHeader ? 1 : 0) + height },
    ...out,
  );
}
