// examples/host-react-demo/src/lib/components/plugin/PluginToggle.tsx
import type { ReactNode } from "react";
import { Toggle } from "@/lib/components/ui/toggle";

interface PluginToggleProps {
  pressed?: boolean;
  defaultPressed?: boolean;
  disabled?: boolean;
  variant?: "default" | "outline";
  size?: "default" | "sm" | "lg";
  className?: string;
  onClick?: (...args: unknown[]) => void | Promise<void>;
  children?: ReactNode;
}

export function PluginToggle({
  pressed,
  defaultPressed,
  disabled,
  variant = "default",
  size = "default",
  className,
  onClick,
  children,
}: PluginToggleProps) {
  const handlePressedChange = () => {
    onClick?.();
  };

  return (
    <Toggle
      pressed={pressed}
      defaultPressed={defaultPressed}
      disabled={disabled}
      variant={variant}
      size={size}
      className={className}
      onPressedChange={handlePressedChange}
    >
      {children}
    </Toggle>
  );
}

// examples/host-svelte-demo/src/lib/components/plugin/PluginToggle.svelte
<script lang="ts">
	import { Toggle } from '../ui/toggle/index.js';
	import type { Snippet } from 'svelte';

	interface Props {
		pressed?: boolean;
		disabled?: boolean;
		variant?: 'default' | 'outline';
		size?: 'default' | 'sm' | 'lg';
		class?: string;
		onclick?: () => void;
		children?: Snippet;
	}

	let { 
		pressed,
		disabled,
		variant = 'default',
		size = 'default',
		class: className,
		onclick,
		children
	}: Props = $props();
</script>

<Toggle
	{pressed}
	{disabled}
	{variant}
	{size}
	class={className}
	onPressedChange={() => onclick?.()}
>
	{#if children}
		{@render children()}
	{/if}
</Toggle>
