// examples/host-react-demo/src/lib/components/plugin/PluginButton.tsx
import type { ReactNode } from "react";
import { Button } from "@/lib/components/ui/button";

type PluginVariant =
  | "primary"
  | "secondary"
  | "outline"
  | "destructive"
  | "ghost";
type ButtonVariant =
  | "default"
  | "secondary"
  | "outline"
  | "destructive"
  | "ghost"
  | "link";

const variantMap: Record<PluginVariant, ButtonVariant> = {
  primary: "default",
  secondary: "secondary",
  outline: "outline",
  destructive: "destructive",
  ghost: "ghost",
};

interface PluginButtonProps {
  title?: string;
  variant?: PluginVariant | ButtonVariant;
  disabled?: boolean;
  className?: string;
  onClick?: (...args: unknown[]) => void | Promise<void>;
  children?: ReactNode;
}

export function PluginButton({
  title,
  variant = "secondary",
  disabled,
  className,
  onClick,
  children,
}: PluginButtonProps) {
  const handleClick = () => {
    onClick?.();
  };

  const mappedVariant =
    variantMap[variant as PluginVariant] ?? (variant as ButtonVariant);

  return (
    <Button
      variant={mappedVariant}
      disabled={disabled}
      className={className}
      onClick={handleClick}
    >
      {children || title}
    </Button>
  );
}

// examples/host-svelte-demo/src/lib/components/plugin/PluginButton.svelte
<script lang="ts">
	import Button from '../ui/button/button.svelte';
	import type { Snippet } from 'svelte';

	interface Props {
		title?: string;
		variant?: 'primary' | 'secondary' | 'outline' | 'destructive' | 'ghost';
		disabled?: boolean;
		class?: string;
		onclick?: () => void | Promise<void>;
		children?: Snippet;
		[key: string]: unknown;
	}

	let { 
		title,
		variant = 'secondary',
		disabled,
		class: className,
		onclick,
		children,
		...rest
	}: Props = $props();

	const variantMap: Record<string, 'default' | 'secondary' | 'outline' | 'destructive' | 'ghost'> = {
		primary: 'default',
		secondary: 'secondary',
		outline: 'outline',
		destructive: 'destructive',
		ghost: 'ghost'
	};

	function handleClick() {
		void onclick?.();
	}
</script>

<Button
	variant={variantMap[variant] ?? 'secondary'}
	{disabled}
	class={className}
	onclick={handleClick}
>
	{#if children}
		{@render children()}
	{:else if title}
		{title}
	{/if}
</Button>
