// packages/host-svelte/src/ComponentRenderer.svelte
<script lang="ts">
	import { getContext } from "svelte";
	import type { UINode } from "@uniview/protocol";
	import { LAYOUT_TAGS, isHandlerIdProp, extractEventName } from "@uniview/protocol";
	import type { PluginController, ComponentRegistry } from "@uniview/host-sdk";
	import type { Component } from "svelte";
	import Self from "./ComponentRenderer.svelte";

	interface Props {
		node: UINode | string;
	}

	let { node }: Props = $props();

	const controller = getContext<PluginController>("uniview:controller");
	const registry = getContext<ComponentRegistry<Component>>("uniview:registry");

	function createHandler(handlerId: string) {
		return async (...args: unknown[]) => {
			await controller.execute(handlerId, args as unknown[]);
		};
	}

	interface TransformedProps {
		attrs: Record<string, unknown>;
		onclick?: () => Promise<void>;
		oninput?: (e: Event) => Promise<void>;
		onchange?: (e: Event) => Promise<void>;
		onsubmit?: (e: Event) => Promise<void>;
		onfocus?: () => Promise<void>;
		onblur?: () => Promise<void>;
		onkeydown?: (e: KeyboardEvent) => Promise<void>;
		onkeyup?: (e: KeyboardEvent) => Promise<void>;
		onmouseenter?: () => Promise<void>;
		onmouseleave?: () => Promise<void>;
	}

	function transformProps(props: Record<string, unknown>): TransformedProps {
		const attrs: Record<string, unknown> = {};
		const result: TransformedProps = { attrs };

		for (const [key, value] of Object.entries(props)) {
			if (key === "children" || key === "key") continue;

			if (isHandlerIdProp(key)) {
				const eventName = extractEventName(key);
				if (eventName && typeof value === "string") {
					const handler = createHandler(value);
					if (eventName === "onChange") {
						result.oninput = handler;
						result.onchange = handler;
					} else if (eventName === "onInput") {
						result.oninput = handler;
					} else if (eventName === "onClick") {
						result.onclick = handler;
					} else if (eventName === "onSubmit") {
						result.onsubmit = handler;
					} else if (eventName === "onFocus") {
						result.onfocus = handler;
					} else if (eventName === "onBlur") {
						result.onblur = handler;
					} else if (eventName === "onKeyDown") {
						result.onkeydown = handler;
					} else if (eventName === "onKeyUp") {
						result.onkeyup = handler;
					} else if (eventName === "onMouseEnter") {
						result.onmouseenter = handler;
					} else if (eventName === "onMouseLeave") {
						result.onmouseleave = handler;
					}
				}
				continue;
			}

			if (key === "className") {
				attrs.class = value;
			} else if (key === "htmlFor") {
				attrs.for = value;
			} else {
				attrs[key] = value;
			}
		}

		return result;
	}

	// Action to attach events dynamically
	function attachEvents(node: HTMLElement, handlers: TransformedProps) {
		const eventMap: Record<string, keyof TransformedProps> = {
			click: 'onclick',
			input: 'oninput',
			change: 'onchange',
			submit: 'onsubmit',
			focus: 'onfocus',
			blur: 'onblur',
			keydown: 'onkeydown',
			keyup: 'onkeyup',
			mouseenter: 'onmouseenter',
			mouseleave: 'onmouseleave',
		};

		const cleanup: (() => void)[] = [];

		for (const [event, propKey] of Object.entries(eventMap)) {
			const handler = handlers[propKey] as ((...args: unknown[]) => void) | undefined;
			if (handler) {
				node.addEventListener(event, handler as EventListener);
				cleanup.push(() => node.removeEventListener(event, handler as EventListener));
			}
		}

		return {
			update(newHandlers: TransformedProps) {
				// Remove old handlers
				cleanup.forEach(fn => fn());
				cleanup.length = 0;
				
				// Add new handlers
				for (const [event, propKey] of Object.entries(eventMap)) {
					const handler = newHandlers[propKey] as ((...args: unknown[]) => void) | undefined;
					if (handler) {
						node.addEventListener(event, handler as EventListener);
						cleanup.push(() => node.removeEventListener(event, handler as EventListener));
					}
				}
			},
			destroy() {
				cleanup.forEach(fn => fn());
			}
		};
	}
</script>

{#if typeof node === "string"}
	{node}
{:else if node.type === "button"}
	{@const p = transformProps(node.props)}
	<button class="cursor-pointer {p.attrs.class || ''}" {...p.attrs} use:attachEvents={p}>
		{#each node.children as child}
			<Self node={child} />
		{/each}
	</button>
{:else if node.type === "input"}
	{@const p = transformProps(node.props)}
	<input {...p.attrs} use:attachEvents={p} />
{:else if node.type === "textarea"}
	{@const p = transformProps(node.props)}
	<textarea {...p.attrs} use:attachEvents={p}></textarea>
{:else if node.type === "select"}
	{@const p = transformProps(node.props)}
	<select {...p.attrs} use:attachEvents={p}>
		{#each node.children as child}
			<Self node={child} />
		{/each}
	</select>
{:else if node.type === "a"}
	{@const p = transformProps(node.props)}
	<a {...p.attrs} use:attachEvents={p}>
		{#each node.children as child}
			<Self node={child} />
		{/each}
	</a>
{:else if node.type === "form"}
	{@const p = transformProps(node.props)}
	<form {...p.attrs} use:attachEvents={p}>
		{#each node.children as child}
			<Self node={child} />
		{/each}
	</form>
{:else if LAYOUT_TAGS.includes(node.type as typeof LAYOUT_TAGS[number])}
	{@const p = transformProps(node.props)}
	<svelte:element this={node.type} {...p.attrs} use:attachEvents={p}>
		{#each node.children as child}
			<Self node={child} />
		{/each}
	</svelte:element>
{:else if registry?.has(node.type)}
	{@const RegisteredComponent = registry.get(node.type)}
	{@const p = transformProps(node.props)}
	{@const textChildren = node.children.filter((child): child is string => typeof child === 'string').join('')}
	{@const nonTextChildren = node.children.filter((child) => typeof child !== 'string')}
	{@const componentProps = {
		...p.attrs,
		// For Button-like components, use text children as title fallback
		title: textChildren || p.attrs.title,
		onclick: p.onclick,
		oninput: p.oninput,
		onchange: p.onchange,
		onsubmit: p.onsubmit,
		onfocus: p.onfocus,
		onblur: p.onblur,
		onkeydown: p.onkeydown,
		onkeyup: p.onkeyup,
	}}
	{#if nonTextChildren.length > 0 || textChildren}
		<RegisteredComponent {...componentProps}>
			{#if textChildren}{textChildren}{/if}
			{#each nonTextChildren as child}
				<Self node={child} />
			{/each}
		</RegisteredComponent>
	{:else}
		<RegisteredComponent {...componentProps} />
	{/if}
{:else}
	<div class="uniview-unknown">Unknown: {node.type}</div>
{/if}

// examples/host-react-demo/src/lib/plugin/ComponentRenderer.tsx
import React from "react";
import type { UINode, JSONValue } from "@uniview/protocol";
import {
  LAYOUT_TAGS,
  isHandlerIdProp,
  extractEventName,
} from "@uniview/protocol";
import { usePluginContext } from "./PluginContext";

interface ComponentRendererProps {
  node: UINode | string;
}

const VOID_ELEMENTS = ["br", "hr", "img", "input", "meta", "link"];

type EventHandler = (...args: unknown[]) => Promise<void>;

interface TransformedProps {
  attrs: Record<string, unknown>;
  onClick?: EventHandler;
  onInput?: EventHandler;
  onChange?: EventHandler;
  onSubmit?: EventHandler;
  onFocus?: EventHandler;
  onBlur?: EventHandler;
  onKeyDown?: EventHandler;
  onKeyUp?: EventHandler;
  onMouseEnter?: EventHandler;
  onMouseLeave?: EventHandler;
}

export function ComponentRenderer({ node }: ComponentRendererProps) {
  const { controller, registry } = usePluginContext();

  if (typeof node === "string") {
    return <>{node}</>;
  }

  function createHandler(handlerId: string): EventHandler {
    return async (...args: unknown[]) => {
      await controller.execute(handlerId, args as JSONValue[]);
    };
  }

  function transformProps(props: Record<string, JSONValue>): TransformedProps {
    const attrs: Record<string, unknown> = {};
    const result: TransformedProps = { attrs };

    for (const [key, value] of Object.entries(props)) {
      if (key === "children" || key === "key") continue;

      if (isHandlerIdProp(key)) {
        const eventName = extractEventName(key);
        if (eventName && typeof value === "string") {
          const handler = createHandler(value);
          if (eventName === "onChange") {
            result.onInput = handler;
            result.onChange = handler;
          } else if (eventName === "onInput") {
            result.onInput = handler;
          } else if (eventName === "onClick") {
            result.onClick = handler;
          } else if (eventName === "onSubmit") {
            result.onSubmit = handler;
          } else if (eventName === "onFocus") {
            result.onFocus = handler;
          } else if (eventName === "onBlur") {
            result.onBlur = handler;
          } else if (eventName === "onKeyDown") {
            result.onKeyDown = handler;
          } else if (eventName === "onKeyUp") {
            result.onKeyUp = handler;
          } else if (eventName === "onMouseEnter") {
            result.onMouseEnter = handler;
          } else if (eventName === "onMouseLeave") {
            result.onMouseLeave = handler;
          }
        }
        continue;
      }

      if (key === "className") {
        attrs.className = value;
      } else if (key === "htmlFor") {
        attrs.htmlFor = value;
      } else {
        attrs[key] = value;
      }
    }

    return result;
  }

  const { type, props, children } = node;
  const p = transformProps(props);

  if (type === "button") {
    return (
      <button
        className={`cursor-pointer ${p.attrs.className || ""}`}
        {...p.attrs}
        onClick={p.onClick}
      >
        {children.map((child, index) => (
          <ComponentRenderer key={index} node={child} />
        ))}
      </button>
    );
  }

  if (type === "input") {
    return <input {...p.attrs} onInput={p.onInput} onChange={p.onChange} />;
  }

  if (type === "textarea") {
    return <textarea {...p.attrs} onInput={p.onInput} onChange={p.onChange} />;
  }

  if (type === "select") {
    return (
      <select {...p.attrs} onChange={p.onChange}>
        {children.map((child, index) => (
          <ComponentRenderer key={index} node={child} />
        ))}
      </select>
    );
  }

  if (type === "a") {
    return (
      <a {...p.attrs} onClick={p.onClick}>
        {children.map((child, index) => (
          <ComponentRenderer key={index} node={child} />
        ))}
      </a>
    );
  }

  if (type === "form") {
    return (
      <form {...p.attrs} onSubmit={p.onSubmit}>
        {children.map((child, index) => (
          <ComponentRenderer key={index} node={child} />
        ))}
      </form>
    );
  }

  if (LAYOUT_TAGS.includes(type as (typeof LAYOUT_TAGS)[number])) {
    const Tag = type as keyof React.JSX.IntrinsicElements;
    const isVoidElement = VOID_ELEMENTS.includes(type);

    if (isVoidElement) {
      return React.createElement(
        Tag,
        p.attrs as React.HTMLAttributes<HTMLElement>,
      );
    }

    return React.createElement(
      Tag,
      p.attrs as React.HTMLAttributes<HTMLElement>,
      children.map((child, index) => (
        <ComponentRenderer key={index} node={child} />
      )),
    );
  }

  if (registry?.has(type)) {
    const RegisteredComponent = registry.get(type)!;
    const textChildren = children
      .filter((child): child is string => typeof child === "string")
      .join("");
    const nonTextChildren = children.filter(
      (child) => typeof child !== "string",
    );

    const componentProps: Record<string, unknown> = {
      ...p.attrs,
      title: textChildren || p.attrs.title,
      onClick: p.onClick,
      onInput: p.onInput,
      onChange: p.onChange,
      onSubmit: p.onSubmit,
      onFocus: p.onFocus,
      onBlur: p.onBlur,
      onKeyDown: p.onKeyDown,
      onKeyUp: p.onKeyUp,
    };

    if (nonTextChildren.length > 0 || textChildren) {
      return React.createElement(
        RegisteredComponent,
        componentProps,
        textChildren,
        ...nonTextChildren.map((child, index) => (
          <ComponentRenderer key={index} node={child} />
        )),
      );
    }

    return React.createElement(RegisteredComponent, componentProps);
  }

  return <div className="uniview-unknown">Unknown: {type}</div>;
}
