// examples/host-vue-demo/src/lib/plugin/ComponentRenderer.vue
<script setup lang="ts">
import { computed, h, type VNode, type Component as VueComponent } from "vue";
import type { UINode, JSONValue } from "@uniview/protocol";
import {
  TEXT_NODE_TYPE,
  textContent,
  LAYOUT_TAGS,
  isHandlerIdProp,
  extractEventName,
} from "@uniview/protocol";
import { usePluginContext } from "./usePluginContext";

interface Props {
  node: UINode | string;
}

const props = defineProps<Props>();
const { controller, registry } = usePluginContext();

const VOID_ELEMENTS = ["br", "hr", "img", "input", "meta", "link"];

type EventHandler = (...args: unknown[]) => Promise<void>;

interface TransformedProps {
  attrs: Record<string, unknown>;
  onClick?: EventHandler;
  onInput?: EventHandler;
  onChange?: EventHandler;
  onSubmit?: EventHandler;
  onFocus?: EventHandler;
  onBlur?: EventHandler;
  onKeydown?: EventHandler;
  onKeyup?: EventHandler;
  onMouseenter?: EventHandler;
  onMouseleave?: EventHandler;
  onWheel?: EventHandler;
}

function createHandler(handlerId: string): EventHandler {
  return async (...args: unknown[]) => {
    await controller.executeHandler(handlerId, args as JSONValue[]);
  };
}

function withoutEvent(handler?: EventHandler) {
  if (!handler) return undefined;
  return () => {
    void handler();
  };
}

function withInputValue(handler?: EventHandler) {
  if (!handler) return undefined;
  return (event: Event) => {
    const target = event.target as
      | HTMLInputElement
      | HTMLTextAreaElement
      | HTMLSelectElement;
    void handler(target.value);
  };
}

// Mirrors the terminal host's wheel payload field for field (TuiWheelEvent:
// deltaY, x, y) so one plugin tree reads its wheel events the same way no
// matter who renders it.
function withWheelDelta(handler?: EventHandler) {
  if (!handler) return undefined;
  return (event: WheelEvent) => {
    void handler({
      deltaY: event.deltaY,
      x: event.clientX,
      y: event.clientY,
    });
  };
}

function submitWithoutEvent(handler?: EventHandler) {
  if (!handler) return undefined;
  return (event: Event) => {
    event.preventDefault();
    void handler();
  };
}

function transformProps(
  nodeProps: Record<string, JSONValue>,
): TransformedProps {
  const attrs: Record<string, unknown> = {};
  const result: TransformedProps = { attrs };

  for (const [key, value] of Object.entries(nodeProps)) {
    if (key === "children" || key === "key") continue;

    if (isHandlerIdProp(key)) {
      const eventName = extractEventName(key);
      if (eventName && typeof value === "string") {
        const handler = createHandler(value);
        if (eventName === "onChange") {
          result.onInput = handler;
          result.onChange = handler;
        } else if (eventName === "onInput") {
          result.onInput = handler;
        } else if (eventName === "onClick") {
          result.onClick = handler;
        } else if (eventName === "onSubmit") {
          result.onSubmit = handler;
        } else if (eventName === "onFocus") {
          result.onFocus = handler;
        } else if (eventName === "onBlur") {
          result.onBlur = handler;
        } else if (eventName === "onKeyDown") {
          result.onKeydown = handler;
        } else if (eventName === "onKeyUp") {
          result.onKeyup = handler;
        } else if (eventName === "onMouseEnter") {
          result.onMouseenter = handler;
        } else if (eventName === "onMouseLeave") {
          result.onMouseleave = handler;
        } else if (eventName === "onWheel") {
          result.onWheel = handler;
        }
      }
      continue;
    }

    if (key === "className") {
      attrs.class = value;
    } else if (key === "htmlFor") {
      attrs.for = value;
    } else {
      attrs[key] = value;
    }
  }

  return result;
}

function renderNode(node: UINode | string): VNode | string {
  if (typeof node === "string") {
    return node;
  }

  if (node.type === TEXT_NODE_TYPE) {
    return node.text ?? "";
  }

  const { type, props: nodeProps, children } = node;
  const p = transformProps(nodeProps);

  const renderChildren = (): VNode[] =>
    children.map((child, index) => {
      const rendered = renderNode(child);
      return typeof rendered === "string"
        ? h("span", { key: index }, rendered)
        : rendered;
    });

  if (type === "button") {
    // The composed class must come AFTER the spread: a later key wins in an
    // object literal, so spreading p.attrs last drops `cursor-pointer`
    // whenever the plugin sets a className.
    return h(
      "button",
      {
        ...p.attrs,
        class: `cursor-pointer ${p.attrs.class || ""}`,
        onClick: withoutEvent(p.onClick),
        onWheel: withWheelDelta(p.onWheel),
      },
      renderChildren(),
    );
  }

  if (type === "input") {
    return h("input", {
      ...p.attrs,
      onInput: withInputValue(p.onInput),
      onChange: withInputValue(p.onChange),
      onWheel: withWheelDelta(p.onWheel),
    });
  }

  if (type === "textarea") {
    return h("textarea", {
      ...p.attrs,
      onInput: withInputValue(p.onInput),
      onChange: withInputValue(p.onChange),
      onWheel: withWheelDelta(p.onWheel),
    });
  }

  if (type === "select") {
    return h(
      "select",
      {
        ...p.attrs,
        onChange: withInputValue(p.onChange),
        onWheel: withWheelDelta(p.onWheel),
      },
      renderChildren(),
    );
  }

  if (type === "a") {
    return h(
      "a",
      {
        ...p.attrs,
        onClick: withoutEvent(p.onClick),
        onWheel: withWheelDelta(p.onWheel),
      },
      renderChildren(),
    );
  }

  if (type === "form") {
    return h(
      "form",
      {
        ...p.attrs,
        onSubmit: submitWithoutEvent(p.onSubmit),
        onWheel: withWheelDelta(p.onWheel),
      },
      renderChildren(),
    );
  }

  if (LAYOUT_TAGS.includes(type as (typeof LAYOUT_TAGS)[number])) {
    const isVoidElement = VOID_ELEMENTS.includes(type);
    const layoutProps = {
      ...p.attrs,
      onWheel: withWheelDelta(p.onWheel),
    };
    if (isVoidElement) {
      return h(type, layoutProps);
    }
    return h(type, layoutProps, renderChildren());
  }

  if (registry?.has(type)) {
    const RegisteredComponent = registry.get(type) as VueComponent;
    const textChildren = children
      .map((child) => textContent(child) ?? "")
      .join("");
    const nonTextChildren = children.filter(
      (child) => textContent(child) === null,
    ) as UINode[];

    const componentProps = {
      ...p.attrs,
      title: textChildren || p.attrs.title,
      onClick: p.onClick,
      onInput: p.onInput,
      onChange: p.onChange,
      onSubmit: p.onSubmit,
      onFocus: p.onFocus,
      onBlur: p.onBlur,
      onKeydown: p.onKeydown,
      onKeyup: p.onKeyup,
      onMouseenter: p.onMouseenter,
      onMouseleave: p.onMouseleave,
      onWheel: p.onWheel,
    };

    if (nonTextChildren.length > 0 || textChildren) {
      return h(RegisteredComponent, componentProps, {
        default: () => [
          textChildren,
          ...nonTextChildren.map((child, index) => {
            const rendered = renderNode(child);
            return typeof rendered === "string"
              ? h("span", { key: index }, rendered)
              : rendered;
          }),
        ],
      });
    }

    return h(RegisteredComponent, componentProps);
  }

  return h("div", { class: "uniview-unknown" }, `Unknown: ${type}`);
}

const renderedNode = computed((): VNode => {
  const result = renderNode(props.node);
  return typeof result === "string" ? h("span", {}, result) : result;
});
</script>

<template>
  <component :is="renderedNode" />
</template>

// examples/host-react-demo/src/lib/plugin/ComponentRenderer.tsx
import React from "react";
import type { UINode, JSONValue } from "@uniview/protocol";
import {
  LAYOUT_TAGS,
  TEXT_NODE_TYPE,
  textContent,
  isHandlerIdProp,
  extractEventName,
} from "@uniview/protocol";
import { usePluginContext } from "./PluginContext";

interface ComponentRendererProps {
  node: UINode | string;
}

const VOID_ELEMENTS = ["br", "hr", "img", "input", "meta", "link"];

type EventHandler = (...args: unknown[]) => Promise<void>;

interface TransformedProps {
  attrs: Record<string, unknown>;
  onClick?: EventHandler;
  onInput?: EventHandler;
  onChange?: EventHandler;
  onSubmit?: EventHandler;
  onFocus?: EventHandler;
  onBlur?: EventHandler;
  onKeyDown?: EventHandler;
  onKeyUp?: EventHandler;
  onMouseEnter?: EventHandler;
  onMouseLeave?: EventHandler;
  onWheel?: EventHandler;
}

export function ComponentRenderer({ node }: ComponentRendererProps) {
  const { controller, registry } = usePluginContext();

  if (typeof node === "string") {
    return <>{node}</>;
  }

  if (node.type === TEXT_NODE_TYPE) {
    return <>{node.text}</>;
  }

  function createHandler(handlerId: string): EventHandler {
    return async (...args: unknown[]) => {
      await controller.executeHandler(handlerId, args as JSONValue[]);
    };
  }

  function transformProps(props: Record<string, JSONValue>): TransformedProps {
    const attrs: Record<string, unknown> = {};
    const result: TransformedProps = { attrs };

    for (const [key, value] of Object.entries(props)) {
      if (key === "children" || key === "key") continue;

      if (isHandlerIdProp(key)) {
        const eventName = extractEventName(key);
        if (eventName && typeof value === "string") {
          const handler = createHandler(value);
          if (eventName === "onChange") {
            result.onInput = handler;
            result.onChange = handler;
          } else if (eventName === "onInput") {
            result.onInput = handler;
          } else if (eventName === "onClick") {
            result.onClick = handler;
          } else if (eventName === "onSubmit") {
            result.onSubmit = handler;
          } else if (eventName === "onFocus") {
            result.onFocus = handler;
          } else if (eventName === "onBlur") {
            result.onBlur = handler;
          } else if (eventName === "onKeyDown") {
            result.onKeyDown = handler;
          } else if (eventName === "onKeyUp") {
            result.onKeyUp = handler;
          } else if (eventName === "onMouseEnter") {
            result.onMouseEnter = handler;
          } else if (eventName === "onMouseLeave") {
            result.onMouseLeave = handler;
          } else if (eventName === "onWheel") {
            result.onWheel = handler;
          }
        }
        continue;
      }

      if (key === "className") {
        attrs.className = value;
      } else if (key === "htmlFor") {
        attrs.htmlFor = value;
      } else {
        attrs[key] = value;
      }
    }

    return result;
  }

  function withoutEvent(handler?: EventHandler): (() => void) | undefined {
    if (!handler) return undefined;
    return () => {
      void handler();
    };
  }

  function withInputValue(
    handler?: EventHandler,
  ): ((event: React.FormEvent<HTMLInputElement | HTMLTextAreaElement>) => void) | undefined {
    if (!handler) return undefined;
    return (event) => {
      void handler(event.currentTarget.value);
    };
  }

  function withSelectValue(
    handler?: EventHandler,
  ): ((event: React.ChangeEvent<HTMLSelectElement>) => void) | undefined {
    if (!handler) return undefined;
    return (event) => {
      void handler(event.currentTarget.value);
    };
  }

  // Mirrors the terminal host's wheel payload field for field (TuiWheelEvent:
  // deltaY, x, y) so one plugin tree reads its wheel events the same way no
  // matter who renders it.
  function withWheelDelta(
    handler?: EventHandler,
  ): ((event: React.WheelEvent<HTMLElement>) => void) | undefined {
    if (!handler) return undefined;
    return (event) => {
      void handler({
        deltaY: event.deltaY,
        x: event.clientX,
        y: event.clientY,
      });
    };
  }

  function submitWithoutEvent(
    handler?: EventHandler,
  ): ((event: React.FormEvent<HTMLFormElement>) => void) | undefined {
    if (!handler) return undefined;
    return (event) => {
      event.preventDefault();
      void handler();
    };
  }

  const { type, props, children } = node;
  const p = transformProps(props);

  if (type === "button") {
    return (
      // The composed className must come AFTER the spread — JSX takes the last
      // occurrence, so spreading p.attrs last drops `cursor-pointer` whenever
      // the plugin sets a className.
      <button
        {...p.attrs}
        className={`cursor-pointer ${p.attrs.className || ""}`}
        onClick={withoutEvent(p.onClick)}
        onWheel={withWheelDelta(p.onWheel)}
      >
        {children.map((child, index) => (
          <ComponentRenderer key={index} node={child} />
        ))}
      </button>
    );
  }

  if (type === "input") {
    return (
      <input
        {...p.attrs}
        onInput={withInputValue(p.onInput)}
        onChange={withInputValue(p.onChange)}
        onWheel={withWheelDelta(p.onWheel)}
      />
    );
  }

  if (type === "textarea") {
    return (
      <textarea
        {...p.attrs}
        onInput={withInputValue(p.onInput)}
        onChange={withInputValue(p.onChange)}
        onWheel={withWheelDelta(p.onWheel)}
      />
    );
  }

  if (type === "select") {
    return (
      <select
        {...p.attrs}
        onChange={withSelectValue(p.onChange)}
        onWheel={withWheelDelta(p.onWheel)}
      >
        {children.map((child, index) => (
          <ComponentRenderer key={index} node={child} />
        ))}
      </select>
    );
  }

  if (type === "a") {
    return (
      <a
        {...p.attrs}
        onClick={withoutEvent(p.onClick)}
        onWheel={withWheelDelta(p.onWheel)}
      >
        {children.map((child, index) => (
          <ComponentRenderer key={index} node={child} />
        ))}
      </a>
    );
  }

  if (type === "form") {
    return (
      <form
        {...p.attrs}
        onSubmit={submitWithoutEvent(p.onSubmit)}
        onWheel={withWheelDelta(p.onWheel)}
      >
        {children.map((child, index) => (
          <ComponentRenderer key={index} node={child} />
        ))}
      </form>
    );
  }

  if (LAYOUT_TAGS.includes(type as (typeof LAYOUT_TAGS)[number])) {
    const Tag = type as keyof React.JSX.IntrinsicElements;
    const isVoidElement = VOID_ELEMENTS.includes(type);
    const layoutProps = {
      ...p.attrs,
      onWheel: withWheelDelta(p.onWheel),
    } as React.HTMLAttributes<HTMLElement>;

    if (isVoidElement) {
      return React.createElement(Tag, layoutProps);
    }

    return React.createElement(
      Tag,
      layoutProps,
      children.map((child, index) => (
        <ComponentRenderer key={index} node={child} />
      )),
    );
  }

  if (registry?.has(type)) {
    const RegisteredComponent = registry.get(type)!;
    const textChildren = children
      .map((child) => textContent(child) ?? "")
      .join("");
    const nonTextChildren = children.filter(
      (child) => textContent(child) === null,
    );

    const componentProps: Record<string, unknown> = {
      ...p.attrs,
      title: textChildren || p.attrs.title,
      onClick: p.onClick,
      onInput: p.onInput,
      onChange: p.onChange,
      onSubmit: p.onSubmit,
      onFocus: p.onFocus,
      onBlur: p.onBlur,
      onKeyDown: p.onKeyDown,
      onKeyUp: p.onKeyUp,
      onMouseEnter: p.onMouseEnter,
      onMouseLeave: p.onMouseLeave,
      onWheel: p.onWheel,
    };

    if (nonTextChildren.length > 0 || textChildren) {
      return React.createElement(
        RegisteredComponent,
        componentProps,
        textChildren,
        ...nonTextChildren.map((child, index) => (
          <ComponentRenderer key={index} node={child} />
        )),
      );
    }

    return React.createElement(RegisteredComponent, componentProps);
  }

  return <div className="uniview-unknown">Unknown: {type}</div>;
}
