// packages/host-svelte/src/PluginHost.svelte
<script lang="ts">
	import { setContext, onMount, onDestroy } from "svelte";
	import type { UINode } from "@uniview/protocol";
	import type { PluginController, ComponentRegistry } from "@uniview/host-sdk";
	import type { Component, Snippet } from "svelte";
	import ComponentRenderer from "./ComponentRenderer.svelte";

	interface Props {
		controller: PluginController;
		registry: ComponentRegistry<Component>;
		loading?: Snippet;
	}

	let { controller, registry, loading }: Props = $props();

	let tree = $state<UINode | null>(null);
	let unsubscribe: (() => void) | null = null;

	setContext("uniview:controller", controller);
	setContext("uniview:registry", registry);

	onMount(async () => {
		unsubscribe = controller.subscribe((newTree) => {
			tree = newTree;
		});
		await controller.connect();
	});

	onDestroy(() => {
		unsubscribe?.();
		controller.disconnect();
	});
</script>

{#if tree}
	<ComponentRenderer node={tree} />
{:else if loading}
	{@render loading()}
{:else}
	<div>Loading...</div>
{/if}

// examples/host-react-demo/src/lib/plugin/PluginHost.tsx
import {
  useEffect,
  useState,
  useRef,
  type ReactNode,
  type ComponentType,
} from "react";
import type { UINode } from "@uniview/protocol";
import type { PluginController, ComponentRegistry } from "@uniview/host-sdk";
import { PluginContext } from "./PluginContext";
import { ComponentRenderer } from "./ComponentRenderer";

interface PluginHostProps {
  controller: PluginController;
  registry: ComponentRegistry<ComponentType>;
  loading?: ReactNode;
}

export function PluginHost({ controller, registry, loading }: PluginHostProps) {
  const [tree, setTree] = useState<UINode | null>(null);
  const controllerRef = useRef(controller);

  useEffect(() => {
    setTree(null);
    controllerRef.current = controller;

    const isActiveController = () => controllerRef.current === controller;

    const unsubscribe = controller.subscribe((newTree) => {
      if (isActiveController()) {
        setTree(newTree);
      }
    });

    controller.connect().catch((err) => {
      console.error("Failed to connect to plugin:", err);
    });

    return () => {
      unsubscribe();
      controller.disconnect();
    };
  }, [controller]);

  return (
    <PluginContext.Provider value={{ controller, registry }}>
      {tree ? (
        <ComponentRenderer node={tree} />
      ) : loading ? (
        loading
      ) : (
        <div>Loading...</div>
      )}
    </PluginContext.Provider>
  );
}
