// examples/host-svelte-demo/src/lib/components/plugin/PluginSwitch.svelte
<script lang="ts">
	import { Switch } from '../ui/switch/index.js';

	interface Props {
		id?: string;
		checked?: boolean;
		disabled?: boolean;
		class?: string;
		onchange?: (checked: boolean) => void;
	}

	let { 
		id,
		checked,
		disabled,
		class: className,
		onchange
	}: Props = $props();
</script>

<Switch
	{id}
	{checked}
	{disabled}
	class={className}
	onCheckedChange={(newChecked) => onchange?.(newChecked)}
/>

// examples/host-react-demo/src/lib/components/plugin/PluginSwitch.tsx
import { Switch } from "@/lib/components/ui/switch";

interface PluginSwitchProps {
  id?: string;
  checked?: boolean;
  defaultChecked?: boolean;
  disabled?: boolean;
  className?: string;
  onChange?: (...args: unknown[]) => void | Promise<void>;
}

export function PluginSwitch({
  id,
  checked,
  defaultChecked,
  disabled,
  className,
  onChange,
}: PluginSwitchProps) {
  const handleCheckedChange = (value: boolean) => {
    onChange?.(value);
  };

  return (
    <Switch
      id={id}
      checked={checked}
      defaultChecked={defaultChecked}
      disabled={disabled}
      className={className}
      onCheckedChange={handleCheckedChange}
    />
  );
}
