// examples/host-vue-demo/src/lib/components/plugin/PluginInput.vue
<script setup lang="ts">
import { Input } from "@/lib/components/ui/input";
import { Label } from "@/lib/components/ui/label";

interface Props {
  id?: string;
  label?: string;
  placeholder?: string;
  type?: string;
  value?: string;
  defaultValue?: string;
  disabled?: boolean;
  class?: string;
  onInput?: (...args: unknown[]) => void;
  onChange?: (...args: unknown[]) => void;
}

const props = defineProps<Props>();

const inputId = props.id || `input-${Math.random().toString(36).slice(2, 9)}`;

function handleInput(event: Event) {
  const target = event.target as HTMLInputElement;
  props.onInput?.(target.value);
  props.onChange?.(target.value);
}
</script>

<template>
  <div class="space-y-2">
    <Label v-if="label" :for="inputId">{{ label }}</Label>
    <Input
      :id="inputId"
      :type="type || 'text'"
      :placeholder="placeholder"
      :model-value="value"
      :default-value="defaultValue"
      :disabled="disabled"
      :class="$props.class"
      @input="handleInput"
    />
  </div>
</template>

// examples/host-react-demo/src/lib/components/plugin/PluginInput.tsx
import type { ChangeEvent } from "react";
import { Input } from "@/lib/components/ui/input";
import { Label } from "@/lib/components/ui/label";

interface PluginInputProps {
  id?: string;
  label?: string;
  placeholder?: string;
  type?: string;
  value?: string;
  defaultValue?: string;
  disabled?: boolean;
  className?: string;
  onInput?: (...args: unknown[]) => void | Promise<void>;
  onChange?: (...args: unknown[]) => void | Promise<void>;
}

export function PluginInput({
  id,
  label,
  placeholder,
  type = "text",
  value,
  defaultValue,
  disabled,
  className,
  onInput,
  onChange,
}: PluginInputProps) {
  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    const newValue = e.target.value;
    onInput?.(newValue);
    onChange?.(newValue);
  };

  const inputId = id || `input-${Math.random().toString(36).slice(2, 9)}`;

  return (
    <div className="space-y-2">
      {label && <Label htmlFor={inputId}>{label}</Label>}
      <Input
        id={inputId}
        type={type}
        placeholder={placeholder}
        value={value}
        defaultValue={defaultValue}
        disabled={disabled}
        className={className}
        onChange={handleChange}
      />
    </div>
  );
}
