// examples/host-svelte-demo/src/lib/components/plugin/PluginInput.svelte
<script lang="ts">
	import Input from '../ui/input/input.svelte';
	import Label from '../ui/label/label.svelte';

	interface Props {
		id?: string;
		label?: string;
		placeholder?: string;
		type?: string;
		value?: string;
		disabled?: boolean;
		class?: string;
		onchange?: (value: string) => void;
	}

	let { 
		id,
		label,
		placeholder,
		type = 'text',
		value,
		disabled,
		class: className,
		onchange
	}: Props = $props();
</script>

<div class="space-y-2">
	{#if label}
		<Label for={id}>{label}</Label>
	{/if}
	<Input
		{id}
		{placeholder}
		{type}
		{value}
		{disabled}
		class={className}
		oninput={(e) => {
			const target = e.target as HTMLInputElement;
			onchange?.(target.value);
		}}
	/>
</div>

// examples/host-vue-demo/src/lib/components/plugin/PluginInput.vue
<script setup lang="ts">
import { Input } from "@/lib/components/ui/input";
import { Label } from "@/lib/components/ui/label";

interface Props {
  id?: string;
  label?: string;
  placeholder?: string;
  type?: string;
  value?: string;
  defaultValue?: string;
  disabled?: boolean;
  class?: string;
  onInput?: (...args: unknown[]) => void;
  onChange?: (...args: unknown[]) => void;
}

const props = defineProps<Props>();

const inputId = props.id || `input-${Math.random().toString(36).slice(2, 9)}`;

function handleInput(event: Event) {
  const target = event.target as HTMLInputElement;
  props.onInput?.(target.value);
  props.onChange?.(target.value);
}
</script>

<template>
  <div class="space-y-2">
    <Label v-if="label" :for="inputId">{{ label }}</Label>
    <Input
      :id="inputId"
      :type="type || 'text'"
      :placeholder="placeholder"
      :model-value="value"
      :default-value="defaultValue"
      :disabled="disabled"
      :class="$props.class"
      @input="handleInput"
    />
  </div>
</template>
