// examples/plugin-solid-api/src/components/Button.ts
import { createElement, spread, insert } from "@uniview/solid-renderer"
import type { AnyNode } from "@uniview/solid-renderer"
import type { JSX } from "solid-js"

export interface ButtonProps {
	children?: JSX.Element
	title?: string
	variant?: "primary" | "secondary" | "outline" | "destructive" | "ghost"
	onClick?: () => void
	disabled?: boolean
	className?: string
}

export function Button(props: ButtonProps): AnyNode {
	const el = createElement("Button")
	spread(el, props, true)
	insert(el, () => props.children)
	return el
}

// examples/plugin-api/src/components/Button.tsx
import { createElement } from "react";
import type { ReactElement, ReactNode } from "react";

export interface ButtonProps {
  children?: ReactNode;
  title?: string;
  variant?: "primary" | "secondary" | "outline" | "destructive" | "ghost";
  onClick?: () => void;
  disabled?: boolean;
  className?: string;
}

export function Button({
  children,
  title,
  variant = "secondary",
  onClick,
  disabled,
  className,
}: ButtonProps): ReactElement {
  return createElement(
    "Button",
    {
      title,
      variant,
      onClick,
      disabled,
      className,
    },
    children,
  );
}
