// examples/host-svelte-demo/src/lib/components/ui/Button.svelte
<script lang="ts">
	import Button from '$lib/components/ui/button/button.svelte';

	interface ButtonProps {
		title?: string;
		icon?: string;
		variant?: 'primary' | 'secondary' | 'outline' | 'destructive' | 'ghost' | 'link';
		shortcut?: string;
		onClick?: () => void;
		class?: string;
	}

	let {
		title,
		icon,
		variant = 'secondary',
		shortcut,
		onClick,
		class: className
	}: ButtonProps = $props();

	function handleClick() {
		onClick?.();
	}

	const variantMap = {
		primary: 'default',
		secondary: 'secondary',
		outline: 'outline',
		destructive: 'destructive',
		ghost: 'ghost',
		link: 'link'
	} as const;
</script>

<Button variant={variantMap[variant] || 'secondary'} onclick={handleClick} class={className}>
	{#if icon}
		<span class="text-base">{icon}</span>
	{/if}
	{#if title}
		<span class="flex-1">{title}</span>
	{/if}
	{#if shortcut}
		<span class="ml-2 rounded bg-secondary px-1.5 py-0.5 text-xs opacity-60">{shortcut}</span>
	{/if}
</Button>

// examples/plugin-api/src/components/Button.tsx
import { createElement } from "react";
import type { ReactElement, ReactNode } from "react";

export interface ButtonProps {
  children?: ReactNode;
  title?: string;
  variant?: "primary" | "secondary" | "outline" | "destructive" | "ghost";
  onClick?: () => void;
  disabled?: boolean;
  className?: string;
}

export function Button({
  children,
  title,
  variant = "secondary",
  onClick,
  disabled,
  className,
}: ButtonProps): ReactElement {
  return createElement(
    "Button",
    {
      title,
      variant,
      onClick,
      disabled,
      className,
    },
    children,
  );
}
