// examples/plugin-solid-api/src/components/Toggle.ts
import { createElement, spread, insert } from "@uniview/solid-renderer"
import type { AnyNode } from "@uniview/solid-renderer"
import type { JSX } from "solid-js"

export interface ToggleProps {
	children?: JSX.Element
	pressed?: boolean
	defaultPressed?: boolean
	disabled?: boolean
	variant?: "default" | "outline"
	size?: "default" | "sm" | "lg"
	onClick?: () => void
	className?: string
}

export function Toggle(props: ToggleProps): AnyNode {
	const el = createElement("Toggle")
	spread(el, props, true)
	insert(el, () => props.children)
	return el
}

// examples/plugin-api/src/components/Toggle.tsx
import { createElement } from "react";
import type { ReactElement, ReactNode } from "react";

export interface ToggleProps {
  children?: ReactNode;
  pressed?: boolean;
  defaultPressed?: boolean;
  disabled?: boolean;
  variant?: "default" | "outline";
  size?: "default" | "sm" | "lg";
  onClick?: () => void;
  className?: string;
}

export function Toggle({
  children,
  pressed,
  defaultPressed,
  disabled,
  variant = "default",
  size = "default",
  onClick,
  className,
}: ToggleProps): ReactElement {
  return createElement(
    "Toggle",
    {
      pressed,
      defaultPressed,
      disabled,
      variant,
      size,
      onClick,
      className,
    },
    children,
  );
}
