// packages/tui-react/src/error-boundary.ts
import { Component, createElement, type ErrorInfo, type ReactElement, type ReactNode } from "react";

/** Props for {@link ErrorOverview}. */
export interface ErrorOverviewProps {
  error: unknown;
  title?: string;
}

/**
 * A readable error panel drawn from `box`/`text` primitives — shown in place of
 * a broken subtree so the terminal renders a full frame instead of a wrecked
 * one. Message only (no stack) so it is deterministic across bindings and safe
 * to assert byte-identical against the Solid overlay.
 */
export function ErrorOverview({ error, title = "Plugin error" }: ErrorOverviewProps): ReactElement {
  const message = error instanceof Error ? error.message : String(error);
  return createElement(
    "box",
    { flexDirection: "column", border: "rounded", padding: 1, role: "alert" },
    createElement("text", { color: "red", bold: true }, title),
    createElement("text", null, message),
  );
}

/** Props for {@link ErrorBoundary}. */
export interface ErrorBoundaryProps {
  fallback: (error: unknown, reset: () => void) => ReactNode;
  children?: ReactNode;
  onError?: (error: unknown, info: ErrorInfo) => void;
}

interface ErrorBoundaryState {
  hasError: boolean;
  error: unknown;
}

/** Catches render errors in its subtree and shows `fallback(error, reset)`. */
export class ErrorBoundary extends Component<ErrorBoundaryProps, ErrorBoundaryState> {
  state: ErrorBoundaryState = { hasError: false, error: null };

  static getDerivedStateFromError(error: unknown): ErrorBoundaryState {
    return { hasError: true, error };
  }

  componentDidCatch(error: unknown, info: ErrorInfo): void {
    this.props.onError?.(error, info);
  }

  private readonly reset = (): void => {
    this.setState({ hasError: false, error: null });
  };

  render(): ReactNode {
    if (this.state.hasError) return this.props.fallback(this.state.error, this.reset);
    return this.props.children;
  }
}

// packages/tui-solid/src/error-boundary.tsx
import { ErrorBoundary, type JSX } from "solid-js";
import { Box, Text } from "./primitives";

/** Props for {@link ErrorOverview}. */
export interface ErrorOverviewProps {
  error: unknown;
  title?: string;
}

/**
 * A readable error panel drawn from `box`/`text` primitives — the Solid twin of
 * `@uniview/tui-react`'s `ErrorOverview`, deliberately identical output (message
 * only, no stack) so the two render byte-identical SVG.
 */
export function ErrorOverview(props: ErrorOverviewProps): JSX.Element {
  const message = (): string =>
    props.error instanceof Error ? props.error.message : String(props.error);
  return (
    <Box flexDirection="column" border="rounded" padding={1} role="alert">
      <Text color="red" bold>
        {props.title ?? "Plugin error"}
      </Text>
      <Text>{message()}</Text>
    </Box>
  );
}

/** Props for {@link TuiErrorBoundary}. */
export interface TuiErrorBoundaryProps {
  children: JSX.Element;
  fallback?: (error: unknown, reset: () => void) => JSX.Element;
}

/**
 * Wraps Solid's own `<ErrorBoundary>` (Solid has no `componentDidCatch`) and
 * defaults its fallback to {@link ErrorOverview}, so a thrown child shows the
 * overlay instead of crashing the render.
 */
export function TuiErrorBoundary(props: TuiErrorBoundaryProps): JSX.Element {
  return (
    <ErrorBoundary
      fallback={(error: unknown, reset: () => void) =>
        props.fallback ? props.fallback(error, reset) : <ErrorOverview error={error} />
      }
    >
      {props.children}
    </ErrorBoundary>
  );
}
