// packages/tui-react/src/index.ts
import { createElement, type ReactElement } from "react";
import {
  HandlerRegistry,
  MutationCollector,
  createRenderer,
  render as reactRender,
  serializeTree,
  unmount,
} from "@uniview/react-renderer";
import {
  AnsiCellSurface,
  FrameClock,
  MemoryCellSurface,
  StyleTable,
  SvgCellSurface,
  TerminalDriver,
  yogaLayoutEngine,
} from "@uniview/tui-core";
import { InputRouter, TuiHost } from "@uniview/host-tui";
import { TuiRuntimeContext } from "./input";
import { TuiClockContext } from "./animation";
import { connectReactDevTools } from "./devtools";
import type {
  CellSurface,
  CommittedOutput,
  LayoutEngine,
  Size,
  TuiInputEvent,
  TtyInput,
  TtyOutput,
} from "@uniview/tui-core";

export {
  AnsiCellSurface,
  FrameClock,
  MemoryCellSurface,
  StyleTable,
  SvgCellSurface,
  TerminalDriver,
  yogaLayoutEngine,
};
export type {
  CellSurface,
  CommittedOutput,
  LayoutEngine,
  Size,
  TuiInputEvent,
  TtyInput,
  TtyOutput,
} from "@uniview/tui-core";

export { VirtualList } from "./virtual-list";
export type { VirtualListProps } from "./virtual-list";
export { Select } from "./select";
export type { SelectProps } from "./select";
export { Panel } from "./panel";
export type { PanelProps } from "./panel";
export { List, listCounter } from "./list";
export type { ListProps } from "./list";
export { Tree, DirectoryTree } from "./tree";
export type { TreeProps, TreeNode, TreeRowMeta, DirectoryTreeProps } from "./tree";
export { Calendar, isoDate } from "./calendar";
export type { CalendarProps } from "./calendar";
export { StatusBar } from "./status-bar";
export type { StatusBarProps, StatusItem } from "./status-bar";
// First-class JSX components for the host primitives: <Box>/<Text>/<RichText>
export { Box, Text, RichText } from "./primitives";
export { Masked } from "./masked";
export type { MaskedProps } from "./masked";
export { Spacer, Newline, Transform } from "./layout-primitives";
export type { NewlineProps, TransformProps } from "./layout-primitives";
export { Static } from "./static";
export type { StaticProps } from "./static";
export { TextInput } from "./text-input";
export type { TextInputProps } from "./text-input";
export { Tabs } from "./tabs";
export type { TabsProps, TabItem } from "./tabs";
export { Table } from "./table";
export type { Column, TableProps, ColumnAlign, SortDirection, SortState } from "./table";
export { useInput, usePaste, TuiRuntimeContext } from "./input";
export { ErrorBoundary, ErrorOverview } from "./error-boundary";
export type { ErrorBoundaryProps, ErrorOverviewProps } from "./error-boundary";
export { connectReactDevTools } from "./devtools";
export type { DevToolsOptions } from "./devtools";
export type {
  BoxProps,
  TextProps,
  RichTextProps,
  TuiCommonProps,
  TuiEventHandlers,
  TuiKeyEvent,
  TuiWheelEvent,
  TuiPointerEvent,
} from "./primitives";

export { ScrollView, Scrollbar, Hoverable, CommandPalette, filterCommands, clampScroll } from "./interactive";
export type {
  ScrollViewProps,
  ScrollbarProps,
  HoverableProps,
  CommandPaletteProps,
  Command,
} from "./interactive";
export { Markdown, StreamingMarkdown, Code, Diff, renderNodeToElement } from "./content";
export type {
  MarkdownProps,
  StreamingMarkdownProps,
  CodeProps,
  DiffProps,
} from "./content";
export { nextFocus, useFocusList } from "./focus";
export { useAnimation, animate, TuiClockContext, TuiClockProvider } from "./animation";
export type { AnimationState, AnimateOptions } from "./animation";

export { BarChart, Histogram, Sparkline, Gauge, LineGauge, LineChart, Scatter } from "./charts";
export { Canvas } from "./canvas";
export type { CanvasProps } from "./canvas";
export { Image } from "./image";
export type { ImageProps } from "./image";
export type {
  BarChartProps,
  HistogramProps,
  SparklineProps,
  GaugeProps,
  LineGaugeProps,
  LineChartProps,
  ScatterProps,
} from "./charts";

export interface TuiReactRootOptions {
  surface: CellSurface;
  size: Size;
  styles?: StyleTable;
  /** Optional committed-output channel backing <Static> (append-only scrollback). */
  committed?: CommittedOutput;
  /** When true, connect React DevTools (dynamically imported behind the flag). */
  devtools?: boolean;
  /** Frame driver for useAnimation/animate. Defaults to a performance.now()-paced clock. */
  clock?: FrameClock;
  /** Layout engine; defaults to the zero-dependency customLayoutEngine. Pass `yogaLayoutEngine` to opt in. */
  layoutEngine?: LayoutEngine;
  /**
   * "full" (default) re-serializes the tree each commit; "incremental" feeds
   * React's mutation batches to the host (the protocol's incremental path).
   */
  mode?: "full" | "incremental";
}

export interface TuiReactRoot {
  /** The underlying terminal host. */
  readonly host: TuiHost;
  /** The frame driver backing useAnimation/animate. */
  readonly clock: FrameClock;
  /** Mount (or replace) the React element. */
  render(element: ReactElement): void;
  /** Route a normalized terminal input event to the React tree. */
  dispatchInput(event: TuiInputEvent): void;
  /** Unmount React and tear down the host. */
  destroy(): void;
}

export interface TuiReactRenderOptions extends Omit<
  TuiReactRootOptions,
  "surface" | "size" | "styles"
> {
  width?: number;
  height?: number;
  input?: TtyInput;
  output?: TtyOutput;
}

export interface TuiReactApp extends TuiReactRoot {
  readonly driver: TerminalDriver;
}

/**
 * Render a React plugin to a terminal {@link CellSurface}. React commits are
 * serialized to UINode and fed to a {@link TuiHost}; an {@link InputRouter}
 * routes input back — click/Enter/Space activate buttons and typing edits the
 * focused text field (firing onChange/onSubmit). React state updates flow
 * through as incremental frames. This is the plan's React "direct mode".
 */
export function createTuiReactRoot(options: TuiReactRootOptions): TuiReactRoot {
  const handle = createRenderer();
  const registry = new HandlerRegistry();

  const host = new TuiHost({
    surface: options.surface,
    size: options.size,
    styles: options.styles,
    committed: options.committed,
    layoutEngine: options.layoutEngine,
    onInvokeHandler: (handlerId, payload) => {
      void registry.execute(handlerId, payload);
    },
  });
  const router = new InputRouter(host);

  const clock =
    options.clock ??
    new FrameClock({
      now: () => performance.now(),
      requestFrame: (frame) => {
        setTimeout(frame, 16);
      },
      diagnostics: host.renderer.diagnostics,
    });

  if (options.devtools) void connectReactDevTools({ enabled: true });

  const syncFull = (): void => {
    const tree = handle.rootInstance
      ? serializeTree(handle.rootInstance, registry)
      : null;
    // A root is always an element (never a bare string) in practice.
    host.setRoot(typeof tree === "string" ? null : tree);
    router.onRender();
  };

  let unsubscribe: () => void;
  if (options.mode === "incremental") {
    handle.mutationCollector = new MutationCollector(registry);
    unsubscribe = handle.subscribeMutations((mutations) => {
      host.applyBatch(mutations);
      router.onRender();
    });
  } else {
    unsubscribe = handle.subscribe(syncFull);
  }

  return {
    host,
    clock,

    render(element: ReactElement): void {
      // React (ConcurrentRoot) commits asynchronously; `sync` runs from the
      // bridge subscription on every commit, painting each frame. The Providers
      // render no host node, so `serializeTree(rootInstance)` is unchanged.
      reactRender(
        createElement(
          TuiClockContext.Provider,
          { value: clock },
          createElement(TuiRuntimeContext.Provider, { value: router }, element),
        ),
        handle,
      );
    },

    dispatchInput(event: TuiInputEvent): void {
      router.dispatch(event);
    },

    destroy(): void {
      unsubscribe();
      unmount(handle);
      host.destroy();
    },
  };
}

export function render(
  element: ReactElement,
  options: TuiReactRenderOptions = {},
): TuiReactApp {
  const input = options.input ?? (process.stdin as unknown as TtyInput);
  const output = options.output ?? (process.stdout as unknown as TtyOutput);
  const styles = new StyleTable();
  const root = createTuiReactRoot({
    surface: new AnsiCellSurface({
      write: (chunk) => output.write(chunk),
      styles,
    }),
    styles,
    size: {
      width: options.width ?? output.columns ?? 80,
      height: options.height ?? output.rows ?? 24,
    },
    committed: options.committed,
    devtools: options.devtools,
    clock: options.clock,
    layoutEngine: options.layoutEngine,
    mode: options.mode,
  });
  const driver = new TerminalDriver({
    input,
    output,
    onEvent: (event) => {
      if (event.type === "resize") {
        root.host.renderer.resize({ width: event.width, height: event.height });
      } else {
        root.dispatchInput(event);
      }
    },
  });

  driver.start();
  root.render(element);

  return {
    host: root.host,
    clock: root.clock,
    driver,
    render: (next) => root.render(next),
    dispatchInput: (event) => root.dispatchInput(event),
    destroy: () => {
      try {
        root.destroy();
      } finally {
        driver.stop();
      }
    },
  };
}

// packages/tui-solid/src/index.ts
import { createRoot } from "solid-js";
import {
  createComponent,
  HandlerRegistry,
  getRootNode,
  render as solidRender,
  resetIdCounter,
  serializeTree,
  setRootNode,
  setUpdateCallback,
  type SolidNode,
} from "@uniview/solid-renderer";
import {
  AnsiCellSurface,
  FrameClock,
  MemoryCellSurface,
  StyleTable,
  SvgCellSurface,
  TerminalDriver,
  yogaLayoutEngine,
} from "@uniview/tui-core";
import { InputRouter, TuiHost } from "@uniview/host-tui";
import { TuiRuntimeContext } from "./input";
import { connectSolidDevTools } from "./devtools";
import { setActiveTuiClock } from "./animation";
import type {
  CellSurface,
  CommittedOutput,
  LayoutEngine,
  Size,
  TuiInputEvent,
  TtyInput,
  TtyOutput,
} from "@uniview/tui-core";

export {
  AnsiCellSurface,
  FrameClock,
  MemoryCellSurface,
  StyleTable,
  SvgCellSurface,
  TerminalDriver,
  yogaLayoutEngine,
};
export type {
  CellSurface,
  CommittedOutput,
  LayoutEngine,
  Size,
  TuiInputEvent,
  TtyInput,
  TtyOutput,
} from "@uniview/tui-core";

export {
  BarChart,
  Gauge,
  Histogram,
  LineChart,
  LineGauge,
  Scatter,
  Sparkline,
} from "./charts";
export { Canvas } from "./canvas";
export type { CanvasProps } from "./canvas";
export { Image } from "./image";
export type { ImageProps } from "./image";
export type {
  BarChartProps,
  GaugeProps,
  HistogramProps,
  LineChartProps,
  LineGaugeProps,
  ScatterProps,
  SparklineProps,
} from "./charts";
export {
  Code,
  Diff,
  Markdown,
  renderNodeToElement,
  StreamingMarkdown,
} from "./content";
export type {
  CodeProps,
  DiffProps,
  MarkdownProps,
  StreamingMarkdownProps,
} from "./content";
export { createFocusList, nextFocus } from "./focus";
export type { FocusList } from "./focus";
export {
  clampScroll,
  CommandPalette,
  filterCommands,
  Hoverable,
  Scrollbar,
  ScrollView,
} from "./interactive";
export type {
  Command,
  CommandPaletteProps,
  HoverableProps,
  ScrollbarProps,
  ScrollViewProps,
} from "./interactive";
export { Tree, DirectoryTree } from "./tree";
export type {
  TreeProps,
  TreeNode,
  TreeRowMeta,
  DirectoryTreeProps,
} from "./tree";
export { Calendar, isoDate } from "./calendar";
export type { CalendarProps } from "./calendar";
export { List, listCounter } from "./list";
export type { ListProps } from "./list";
export { Select } from "./select";
export type { SelectProps } from "./select";
export { VirtualList } from "./virtual-list";
export type { VirtualListProps } from "./virtual-list";
export { Panel } from "./panel";
export type { PanelProps } from "./panel";
export { Box, RichText, Text } from "./primitives";
export type {
  BoxProps,
  RichTextProps,
  TextProps,
  TuiCommonProps,
} from "./primitives";
export { Masked } from "./masked";
export type { MaskedProps } from "./masked";
export { Spacer, Newline, Transform } from "./layout-primitives";
export type { NewlineProps, TransformProps } from "./layout-primitives";
export { Static } from "./static";
export type { StaticProps } from "./static";
export { TextInput } from "./text-input";
export type { TextInputProps } from "./text-input";
export { Tabs } from "./tabs";
export type { TabsProps, TabItem } from "./tabs";
export { Table } from "./table";
export type {
  Column,
  TableProps,
  ColumnAlign,
  SortDirection,
  SortState,
} from "./table";
export { useInput, usePaste, TuiRuntimeContext } from "./input";
export { TuiErrorBoundary, ErrorOverview } from "./error-boundary";
export type {
  TuiErrorBoundaryProps,
  ErrorOverviewProps,
} from "./error-boundary";
export { connectSolidDevTools } from "./devtools";
export type { DevToolsOptions } from "./devtools";
export {
  useAnimation,
  animate,
  getActiveTuiClock,
  setActiveTuiClock,
} from "./animation";
export type { AnimationState, AnimateOptions } from "./animation";
export { StatusBar } from "./status-bar";
export type { StatusBarProps, StatusItem } from "./status-bar";

export interface TuiSolidRootOptions {
  surface: CellSurface;
  size: Size;
  styles?: StyleTable;
  /** Optional committed-output channel backing <Static> (append-only scrollback). */
  committed?: CommittedOutput;
  /** When true, connect Solid DevTools (dynamically imported behind the flag). */
  devtools?: boolean;
  /** Frame driver for useAnimation/animate. Defaults to a performance.now()-paced clock. */
  clock?: FrameClock;
  /** Layout engine; defaults to the zero-dependency customLayoutEngine. Pass `yogaLayoutEngine` to opt in. */
  layoutEngine?: LayoutEngine;
}

export interface TuiSolidRoot {
  /** The underlying terminal host. */
  readonly host: TuiHost;
  /** The frame driver backing useAnimation/animate. */
  readonly clock: FrameClock;
  /** Mount a Solid root component. */
  render(App: () => unknown): void;
  /** Route a normalized terminal input event to the Solid tree. */
  dispatchInput(event: TuiInputEvent): void;
  /** Dispose the Solid root and tear down the host. */
  destroy(): void;
}

export interface TuiSolidRenderOptions extends Omit<
  TuiSolidRootOptions,
  "surface" | "size" | "styles"
> {
  width?: number;
  height?: number;
  input?: TtyInput;
  output?: TtyOutput;
}

export interface TuiSolidApp extends TuiSolidRoot {
  readonly driver: TerminalDriver;
}

/**
 * Render a Solid plugin to a terminal {@link CellSurface}. Solid's fine-grained
 * reactivity commits synchronously; each update serializes to UINode and feeds
 * a {@link TuiHost}, and input routes back exactly as in the React adapter.
 * Together with @uniview/tui-react this proves the framework-agnostic host.
 *
 * Note: solid-renderer uses a single module-global root, so one Solid root may
 * be active per process at a time.
 */
export function createTuiSolidRoot(options: TuiSolidRootOptions): TuiSolidRoot {
  const registry = new HandlerRegistry();

  const host = new TuiHost({
    surface: options.surface,
    size: options.size,
    styles: options.styles,
    committed: options.committed,
    layoutEngine: options.layoutEngine,
    onInvokeHandler: (handlerId, payload) => {
      void registry.execute(handlerId, payload);
    },
  });
  const router = new InputRouter(host);

  const clock =
    options.clock ??
    new FrameClock({
      now: () => performance.now(),
      requestFrame: (frame) => {
        setTimeout(frame, 16);
      },
      diagnostics: host.renderer.diagnostics,
    });
  setActiveTuiClock(clock);

  if (options.devtools) void connectSolidDevTools({ enabled: true });

  const sync = (): void => {
    const container = getRootNode();
    const appRoot = container?.children[0] ?? null;
    const tree = appRoot ? serializeTree(appRoot, registry) : null;
    host.setRoot(tree && typeof tree !== "string" ? tree : null);
    router.onRender();
  };

  setUpdateCallback(sync);

  let dispose: (() => void) | null = null;

  return {
    host,
    clock,

    render(App: () => unknown): void {
      resetIdCounter();
      const container: SolidNode = {
        _type: "element",
        id: "__root",
        type: "div",
        props: {},
        children: [],
        parent: null,
      };
      setRootNode(container);
      dispose = createRoot((disposeRoot) => {
        solidRender(
          () =>
            createComponent(TuiRuntimeContext.Provider, {
              value: router,
              get children() {
                return App() as SolidNode;
              },
            }) as SolidNode,
          container,
        );
        return disposeRoot;
      });
      sync();
    },

    dispatchInput(event: TuiInputEvent): void {
      router.dispatch(event);
    },

    destroy(): void {
      dispose?.();
      dispose = null;
      setUpdateCallback(() => {});
      setActiveTuiClock(null);
      host.destroy();
    },
  };
}

export function render(
  App: () => unknown,
  options: TuiSolidRenderOptions = {},
): TuiSolidApp {
  const input = options.input ?? (process.stdin as unknown as TtyInput);
  const output = options.output ?? (process.stdout as unknown as TtyOutput);
  const styles = new StyleTable();
  const root = createTuiSolidRoot({
    surface: new AnsiCellSurface({
      write: (chunk) => output.write(chunk),
      styles,
    }),
    styles,
    size: {
      width: options.width ?? output.columns ?? 80,
      height: options.height ?? output.rows ?? 24,
    },
    committed: options.committed,
    devtools: options.devtools,
    clock: options.clock,
    layoutEngine: options.layoutEngine,
  });
  const driver = new TerminalDriver({
    input,
    output,
    onEvent: (event) => {
      if (event.type === "resize") {
        root.host.renderer.resize({ width: event.width, height: event.height });
      } else {
        root.dispatchInput(event);
      }
    },
  });

  driver.start();
  try {
    root.render(App);
  } catch (error) {
    try {
      root.destroy();
    } catch {
      // Preserve the initial mount error after attempting root cleanup.
    } finally {
      driver.stop();
    }
    throw error;
  }

  return {
    host: root.host,
    clock: root.clock,
    driver,
    render: (next) => root.render(next),
    dispatchInput: (event) => root.dispatchInput(event),
    destroy: () => {
      try {
        root.destroy();
      } finally {
        driver.stop();
      }
    },
  };
}
